name: Jardingue
description: "Application de gestion de potager intelligente"
publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Base de données locale
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1

  # Réseau & API
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4

  # Géolocalisation
  geolocator: ^13.0.2

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Utilitaires
  intl: ^0.20.2
  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.0
  json_serializable: ^6.9.5
  drift_dev: ^2.26.0

  # App icon generation
  flutter_launcher_icons: ^0.14.4

  # Native splash generation
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true


flutter_native_splash:
  color: "#F3EDE6"
  image: "assets/splash/splash.png"
  fullscreen: true

  android_12:
    color: "#F3EDE6"
    image: "assets/splash/splash_android12.png"
    icon_background_color: "#F3EDE6"




flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/icon/
    - assets/splash/
